name = "DIY Label Widget"
type = "app_embed"

[settings]
  [[settings.fields]]
  key = "enabled"
  type = "boolean"
  name = "Enable DIY Label"
  description = "Show local printing options on product pages"
  default = true

  [[settings.fields]]
  key = "theme"
  type = "select"
  name = "Widget Theme"
  description = "Choose the appearance of the widget"
  default = "light"
  options = [
    { label = "Light", value = "light" },
    { label = "Dark", value = "dark" },
    { label = "Auto", value = "auto" }
  ]

  [[settings.fields]]
  key = "search_radius"
  type = "number_integer"
  name = "Search Radius (miles)"
  description = "How far to search for print shops"
  default = 25
  min = 5
  max = 100

  [[settings.fields]]
  key = "show_on_all_products"
  type = "boolean"
  name = "Show on All Products"
  description = "Display widget on all products (otherwise only enabled products)"
  default = false

  [[settings.fields]]
  key = "api_url"
  type = "url"
  name = "API URL"
  description = "DIY Label API endpoint"
  default = "https://increasing-exercise-calculation-yo.trycloudflare.com"