# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f503cdb124d31ddda41aa93760f8d8f9"
name = "diy-label"
handle = "diy-label"
application_url = "https://james-gently-extraction-remark.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,write_orders"

[auth]
redirect_urls = ["https://james-gently-extraction-remark.trycloudflare.com/auth/callback", "https://james-gently-extraction-remark.trycloudflare.com/auth/shopify/callback", "https://james-gently-extraction-remark.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
