# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "YOUR_ACTUAL_CLIENT_ID_HERE"
name = "diy-label"
handle = "diy-label"
application_url = "https://spirits-plumbing-definitions-obituaries.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://spirits-plumbing-definitions-obituaries.trycloudflare.com/auth/callback",
  "https://spirits-plumbing-definitions-obituaries.trycloudflare.com/auth/shopify/callback", 
  "https://spirits-plumbing-definitions-obituaries.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false