# Learn more about configuring your extension at https://shopify.dev/docs/apps/checkout/configuration

api_version = "2025-04"

[[extensions]]
type = "checkout_ui_extension"
name = "DIY Label Checkout"
handle = "diy-label-checkout"

[extensions.capabilities]
network_access = true
block_progress = false

[extensions.settings]
[[extensions.settings.fields]]
key = "api_url"
type = "single_line_text_field"
name = "API URL"
description = "DIY Label API endpoint"
default = "https://spirits-plumbing-definitions-obituaries.trycloudflare.com"

[[extensions.settings.fields]]
key = "mapbox_token"
type = "single_line_text_field"
name = "Mapbox Token"
description = "Mapbox access token for maps"