# Learn more about configuring your extension at https://shopify.dev/docs/apps/app-extensions/configuration

api_version = "2025-04"

[[extensions]]
type = "theme_app_extension"
name = "DIY Label"
handle = "diy-label"

  [[extensions.app_embeds]]
  name = "DIY Label Global"
  handle = "diy-label-global"

  [[extensions.blocks]]
  name = "DIY Label Widget"
  handle = "diy-label-widget"

  [[extensions.sections]]
  name = "DIY Label Section"
  handle = "diy-label-section"