name = "diy-label"
type = "app_embed"

[settings]
  [[settings.fields]]
  key = "enabled"
  name = "Enable DIY Label"
  description = "Show local printing options on product pages"
  type = "boolean"
  default = true

  [[settings.fields]]
  key = "widget_theme"
  name = "Widget Theme"
  description = "Choose the appearance of the widget"
  type = "single_select"
  default = "light"
    [settings.fields.options]
    light = "Light"
    dark = "Dark"
    auto = "Auto"

  [[settings.fields]]
  key = "default_radius"
  name = "Search Radius (miles)"
  description = "Default radius for finding nearby print shops"
  type = "number_integer"
  default = 25

  [[settings.fields]]
  key = "show_on_all_products"
  name = "Show on All Products"
  description = "Display widget on all products (overrides per-product settings)"
  type = "boolean"
  default = false