# Learn more about configuring your extension at https://shopify.dev/docs/apps/app-extensions/configuration

api_version = "2025-04"

[[extensions]]
type = "theme_app_extension"
name = "DIY Label"
handle = "diy-label"

# No app_embeds configuration - not supported in theme app extensions