# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-04"

[[extensions]]
name = "DIY Label"
handle = "diy-label"
type = "ui_extension"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension's source code.
[[extensions.targeting]]
module = "./src/local-delivery.tsx"
target = "purchase.checkout.shipping-option-list.render-after"

[[extensions.targeting]]
module = "./src/local-pick-up.tsx"
target = "purchase.checkout.pickup-location-list.render-before"

[extensions.capabilities]
# Gives your extension access to directly query Shopify's storefront API.
api_access = true
network_access = true
